### ISSUE TITLE
RevitLauncher.pfx not found

### ISSUE THREAD

**Issue by chuongmep** [Zhuangkh/RevitLauncher#1]
Dear Zhuangkh,  you can share file RevitLauncher.pfx ?

**Comment by Zhuangkh** [comment]
hi chuongmep,
In general, assembly signing is the recommended way to handle COM registrations. You can just recreate a key file in visual studio and use it.

**Comment by chuongmep** [comment]
> hi chuongmep,
> 
> In general, assembly signing is the recommended way to handle COM registrations. You can just recreate a key file in visual studio and use it.
Thanks you.I like project this.
