### ISSUE TITLE
Not Found Context Menu

### ISSUE THREAD

**Issue by chuongmep** [Zhuangkh/RevitLauncher#2]
Hi Zhuangkh,
I has install msi and it running in revit, but im canot see any context menu to check  version, you have any demo for that ?

**Comment by Zhuangkh** [comment]
Hi chuongmep,

If the installation is successful, when you open the right-click menu on a  RVT (RFA..) file, you can see the options shown like the image below.

![image](https://user-images.githubusercontent.com/30818313/109116216-23c92680-777b-11eb-9c07-1501049d79a1.png)

There may be a bug in the current version of the installation script. I used [SharpShell's SRM](https://github.com/dwmkerr/sharpshell/blob/master/docs/installing/installing.md#installing-with-srm) program to perform the installation. You can try to manually execute `srm install RevitLauncher.dll` from the `C:\ProgramData\Autodesk\ApplicationPlugins\RevitLauncher.bundle\RevitLauncher` path.

I will check and fix it later 😸 .

**Comment by chuongmep** [comment]
Thanks for reply , i will try with SharpShell's SRM.

**Comment by Zhuangkh** [comment]
Sorry for taking so long to update😭
I have updated the code, you can try the releases installer.
